---
abstract: 'A tftp-server, implemented through POE'
author:
  - 'Jan Henning Thorsen, C<< <pm at flodhest.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-TFTPd
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  POE: 1.284
  POE::Wheel::UDP: 0.02
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=POE-Component-TFTPd
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jhthorsen/poe-component-tftpd
version: 0.03
