---
abstract: 'A tftp-server, implemented through POE'
author:
  - 'Jan Henning Thorsen, C<< <pm at flodhest.net> >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-TFTPd
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  POE::Filter::Stream: 0
  POE::Wheel::UDP: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
